name: smart_helmet
description: A FYP that connects your helment with your mobile device and detects crashes to inform the relevant emergency authorities and family members.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.1
  flutter_contacts: ^1.1.6
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  assets:
    - svgs/

  uses-material-design: true